# Flask
DEBUG = False
TESTING = False

# Auth
AUTH_KEEP_ALIVE_TIME = 300

# Custom error codes
ERROR_CODE_VALIDATION = 100
ERROR_CODE_DUPLICATE = 101

ERROR_CODE_AUTH = 102
ERROR_CODE_AUTH_NOT_PROVIDED = 103
ERROR_CODE_AUTH_REQUIRED = 104
ERROR_CODE_AUTH_FAILED = 105

ERROR_CODE_NOT_EXIST = 404