# Flask
DEBUG = False
TESTING = False

# Auth
AUTH_KEEP_ALIVE_TIME = 300

# Image
IMAGE_THUMBNAIL = (32, 32, True)  # w, h, fill_mode:true | scale_mode: false

# Custom error codes
ERROR_CODE_NO_INCOMING_FILE_DATA = 98
ERROR_CODE_NO_INCOMING_JSON_DATA = 99

ERROR_CODE_VALIDATION = 100
ERROR_CODE_DUPLICATE = 101

ERROR_CODE_AUTH = 102
ERROR_CODE_AUTH_NOT_PROVIDED = 103
ERROR_CODE_AUTH_BAD_PROVIDED = 104
ERROR_CODE_AUTH_FAILED = 105

ERROR_CODE_NOT_EXIST = 404